version: '2'
services:
#  logstash:
#    image: ${LOGSTASH_IMAGE}
#    ports:
#      - "12345:12345"
#    volumes:
#      - ./elastic_data/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./elastic_data/pipeline:/usr/share/logstash/pipeline/
#    links:
#      - "elasticsearch"

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    expose:
      - 9200
    ports:
      - "9200:9200"
    volumes:
      - ./elastic_data/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic_data/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=${PASSWORD}

  kibana:
    image: ${KIBANA_IMAGE}
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    volumes:
      - ./elastic_data/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./elastic_data/security:/security
